# Generated by Django 4.2.23 on 2025-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
